scaleoutsystems/stackn

.gitignore, components/studio/scripts/run_web.sh, components/studio/studio/wsgi.py
Volumes are mounted in special directory with telepresence, so this ensures studio gets the right settings.
=> Ensures telepresence gets the right settings module

components/studio/models/templates/models_details.html, components/studio/models/templates/models_details_public.html, components/studio/reports/templates/report_confirm_delete.html, components/studio/reports/templates/reports_add.html, components/studio/reports/templates/reports_details.html, components/studio/reports/templates/reports_details_generator.html, components/studio/reports/templates/reports_details_public.html, components/studio/reports/templates/reports_list.html, components/studio/templates/baseproject.html
=> Change Reports to Metrics in the FE part of the application

components/studio/deployments/views.py
=> Load only project related deployments

components/studio/models/templates/models_cards.html
=> Hided description when not available on a db level

.github/workflows/build-studio.yaml, components/studio/files/helpers.py, components/studio/files/tests.py, components/studio/projects/tests.py, components/studio/reports/helpers.py, components/studio/reports/tests.py, components/studio/set_minio_keys.py
I have started adding unit tests across the different applications in _STACKn_. Modules covered with tests so far:
- files
- reports
- projects
=> Added Unit Tests to some of the modules in STACKn

components/file-controller/Dockerfile, components/file-controller/requirements.txt, components/file-controller/serve.py, components/studio/projects/forms.py, components/studio/projects/models.py, components/studio/projects/templates/settings.html, components/studio/projects/urls.py, components/studio/projects/views.py
Changes have been done to the following STACKn components:
- file-controller
- studio
_file-controller_
- added requirements.txt and adjusted Dockerfile respectively
- added new endpoint for publishing a project on GitHub
_studio_
- added section in the Settings page where the admin can push the project's directory to GitHub
=> (feature) Publish project on GitHub through STACKn studio

components/studio/docker-compose.yml
=> Updated docker-compose.yml

components/studio/datasets/templates/dataset_page.html, components/studio/datasets/templates/dataset_path_page.html, components/studio/deployments/templates/deploy/list.html, components/studio/experiments/templates/experiments/index.html, components/studio/labs/templates/labs/index.html, components/studio/models/templates/model_confirm_delete.html, components/studio/models/templates/models_list.html, components/studio/projects/templates/index_projects.html, components/studio/projects/templates/project.html, components/studio/projects/templates/settings.html, components/studio/reports/templates/report_confirm_delete.html, components/studio/reports/templates/reports_add.html, components/studio/reports/templates/reports_details.html, components/studio/reports/templates/reports_details_generator.html, components/studio/reports/templates/reports_list.html, components/studio/static/css/project.css, components/studio/static/css/studio.css, components/studio/templates/base.html
Closes:
- STACKN-7
- STACKN-21
- STACKN-29
=> UI additions and refinements

cli/scaleout/studioclient.py, components/studio/datasets/templates/dataset_page.html, components/studio/datasets/templates/dataset_path_page.html, components/studio/datasets/views.py, components/studio/deployments/helpers.py, components/studio/deployments/models.py, components/studio/labs/views.py, components/studio/projects/helpers.py, components/studio/projects/models.py, components/studio/projects/templates/settings.html, components/studio/projects/tests.py, components/studio/projects/views.py, components/studio/reports/helpers.py
Refactored code accordingly within STACKn and Scaleout CLI; Added Unit Tests.
More info in Jira - [https://scaleoutsystems.atlassian.net/browse/STACKN-52]
=> Encoding MiniO keys before storing them in the database.

components/studio/models/templates/models_details.html, components/studio/models/urls.py, components/studio/models/views.py
Functionality is available under the model's card for authenticated users only.
More info -> [JIRA](https://scaleoutsystems.atlassian.net/browse/STACKN-51)
=> Added possibility to change model's access level after creation.

cli/scaleout/cli/create_cmd.py, components/studio/deployments/models.py, components/studio/deployments/templates/deploy/list.html, components/studio/deployments/views.py, components/studio/models/templates/models_details.html, components/studio/models/templates/models_details_public.html, components/studio/models/urls.py, components/studio/models/views.py, components/studio/projects/fixtures/data.json
Instead of something like: model-tag.project.domain.com, we have something like: domain.com/project-slug/serve/model/tag
=> Serving with path-based routing works

components/studio/experiments/jobs.py, components/studio/experiments/templates/experiments/index.html, components/studio/experiments/views.py
Changed configuration of the k8s job so that it doesn't break the execution workflow anymore as well as fixed typo in the HTML template.
Optimized imports in the edited files.
More info -> [JIRA](https://scaleoutsystems.atlassian.net/browse/STACKN-88)
=> Fixed broken functionality in the Experiments module.

components/studio/deployments/models.py, components/studio/deployments/templates/deploy/list.html, components/studio/deployments/views.py, components/studio/monitor/helpers.py, components/studio/projects/forms.py, components/studio/projects/templates/settings.html, components/studio/projects/urls.py, components/studio/projects/views.py
STACKN-101 Show model deployment status (pods up/total pods) in deployment overview.
=> Stackn 101

components/studio/deployments/forms.py, components/studio/deployments/templates/deploy/settings.html, components/studio/deployments/views.py, components/studio/static/css/project.css
[JIRA](https://scaleoutsystems.atlassian.net/browse/STACKN-121)
=> Set resource limits for deployments

components/studio/labs/views.py, components/studio/models/views.py, components/studio/projects/admin.py, components/studio/projects/models.py, components/studio/projects/templates/project.html, components/studio/projects/templates/project_activity.html, components/studio/projects/urls.py, components/studio/projects/views.py, components/studio/reports/helpers.py, components/studio/reports/views.py, components/studio/templates/baseproject.html
Added ProjectLog model class.
Added logs within STACKn modules.
Refactored UI - fixed select item, introduced time period for the logs, render the demanded logs only.
[JIRA](https://scaleoutsystems.atlassian.net/browse/STACKN-127)
=> Project Activity

components/studio/api/views.py, components/studio/deployments/models.py
Describe your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.
=> Review changes

docs/_navbar.md, docs/releasenotes.md
Added release notes to STACKn documentation. 
=> Added release notes to STACKn documentation

README.md, docs/INSTALL.md, docs/README.md
Documentation update before releasing STACKn v0.3.0
[STACKn-186](https://scaleoutsystems.atlassian.net/browse/STACKN-186)
=> Fixed docs before the release

components/chart-controller/controller/controller.py, components/studio/deployments/models.py
- [X ] Ready
The user can specify which buckets (arbitrary number) from the Minio instance should be mounted in the deployed container.
- [ X] New feature
- [ X] This pull request is against **develop** branch (not applicable for hotfixes)
=> Option to mount any buckets into a deployment from the local Minio store

docs/INSTALL.md
Updated the INSTALL.md installation guide with instructions for Windows 10.
=> Added installation instructions for WIndows.

components/studio/models/views.py, docs/releasenotes.md
[Go to JIRA](https://scaleoutsystems.atlassian.net/browse/STACKN-154)
=> Don't show public models after the corresponding project has been removed.

.gitignore, components/chart-controller/controller/controller.py, components/studio/deployments/models.py, components/studio/models/views.py, components/studio/projects/templates/settings.html, components/studio/projects/urls.py, components/studio/projects/views.py, docs/releasenotes.md
- Project's detailed page is now listing only the related activity logs
- Public models are no more shown after the corresponding project has been removed
- New improved functionality for adding users as members to your project
=> STACKn v0.4.0

cli/scaleout/auth.py
Describe your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.
=> Fix login for insecure deployments

components/studio/models/templates/models_details.html, components/studio/models/templates/models_details_public.html
[Go to JIRA](https://scaleoutsystems.atlassian.net/browse/STACKN-204)
=> Removed hyperlink and double / from deployment's endpoint URL.

.github/workflows/build-studio.yaml
Describe your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.
=> Introduce github build number as image tag

components/studio/monitor/templates/monitor_new.html, components/studio/monitor/views.py, components/studio/projects/templates/project.html, components/studio/projects/templates/project_readme.html, components/studio/projects/templates/settings.html, components/studio/projects/views.py, components/studio/templates/base.html, docs/releasenotes.md
Quick navigation between projects.
=> Quick navigation between projects

components/studio/projects/templates/settings.html
Edit project description without erasing all the text.
=> Edit project description without erasing all the text

components/studio/api/APIpermissions.py, components/studio/api/views.py
Describe your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.
=> STACKn-292

components/studio/projects/models.py
This hotfix is meant to address issue #237. A custom data validation/clean method has been added for the _projects_ application, by modifying `components/studio/projects/models.py`.
- https://docs.djangoproject.com/en/3.2/ref/models/instances/#validating-objects
closes #237 
Steps for reproducing the issue (and therefore obtaining similar screenshots' output) shown in this thread #237:
- Deploy STACKn **from either main or the develop branch**
- Create a STACKn default project and append trailing spaces when typing the project name
- Create a Jupyter Lab app
- Open a terminal within jupyter and try to run stackn cli commands. Many should fail as explained in #237.
- From the same terminal, run `cat $HOME/.scaleout/stackn.json`. With the trailing spaces at the end you should see something …
=> Bugfix for issue #237

cli/stackn/auth.py, cli/stackn/create.py, cli/stackn/delete.py, cli/stackn/get.py, cli/stackn/main.py, cli/stackn/stackn.py
This hotfix is meant to address issue #238. Stackn CLI was rather unstable; so this hotfix aims at making the CLI more stable  and more user friendly via better feedback messages.
closes #238
Steps for reproducing the issue:
- Deploy a STACKn **from either main or the develop branch**
- Create at least one project template in order to be able to create a project and start apps
- Open a terminal either locally on your machine or within Jupyter in STACKn and try to run stackn cli commands such as: get, create and delete. Many should not work properly.
Steps for testing the patch code:
- Deploy a STACKn **from either main or the develop branch**
- Create at least one project template in order to be able to create a project and start apps
- Open a terminal either, again locally or in a …
=> Bugfix for Issues 238

components/studio/requirements.txt
Fix for ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' conflict with dash for studio
celery-beat      |     from .dash_demo import app
celery-beat      |   File "/app/monitor/dash_demo.py", line 8, in <module>
celery-beat      |     import dash
celery-beat      |   File "/usr/local/lib/python3.8/site-packages/dash/__init__.py", line 5, in <module>
celery-beat      |     from .dash import Dash, no_update  # noqa: F401,E402
celery-beat      |   File "/usr/local/lib/python3.8/site-packages/dash/dash.py", line 22, in <module>
celery-beat      |     from werkzeug.debug.tbtools import get_current_traceback
celery-beat      | ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' …
=> Fix ImportError: 'get_current_traceback' from 'werkzeug.debug.tbtools'

components/studio/charts/apps/docker-registry/chart/templates/ingress.yaml, components/studio/charts/apps/jupyter-lab/chart/templates/project-labs-deployment.yaml, components/studio/charts/apps/jupyter-lab/chart/templates/project-labs-ingress.yaml, components/studio/charts/apps/minio/chart/templates/project-s3-ingress.yaml, components/studio/charts/apps/mlflow-serve/chart/templates/ingress.yaml, components/studio/charts/apps/mlflow/chart/templates/ingress.yaml, components/studio/charts/apps/mongo-express/chart/templates/ingress.yaml, components/studio/charts/apps/pytorch-serve/chart/templates/ingress.yaml, components/studio/charts/apps/rstudio/chart/templates/ingress.yaml, components/studio/charts/apps/tensorflow-serve/chart/templates/ingress.yaml, components/studio/charts/apps/vscode/chart/templates/ingress.yaml, components/studio/charts/apps/wetty-terminal/chart/templates/ingress.yaml
- add http to MLFLOW_TRACKING_URI env var
- change auth-signin domain to external
=> add protocol for mlflow service uri

components/studio/apps/fixtures/periodic_tasks_fixtures.json, components/studio/apps/serialize.py, components/studio/apps/tasks.py, components/studio/models/models.py, components/studio/models/tests.py, components/studio/projects/fixtures/projects_templates.json, components/studio/projects/models.py
Enables sync between mlflow model registry and stackn models using celery tasks.
Default project template updated with extra parameters (values) for volumes, fixing issue where permission denied on write.
=> MLFlow model registry sync

components/studio/studio/settings.py
small fix to SESSION_COOKIE_DOMAIN
=> fix session cookie domain

components/studio/common/templates/registration/registration_complete.html, components/studio/common/urls.py, components/studio/common/views.py
New view for when account registration is successful (when INACTIVE_USERS=True)
=> feature/SK-163 Add new view and redirect after account registration

cli/tests/tests.py
Minor fix to path of config file in unittest.
=> Fix path to config file

cli/stackn/create.py, components/studio/projects/fixtures/projects_templates.json
Jupyter-stackn image is now pushed to github registry. Update image in the jupyter lab environment in project templates fixtures.
Additional: Minor fix to create project (cli), default project set to "default"
=> Feature/SK-165 Update jupyter image in project template

components/studio/Dockerfile
Stackn user did not have write access to copied folder. Fixed by changing stackn to be owner of folder.
=> Fix owner of copied folder 

components/studio/apps/tasks.py
In apps/tasks.py some command had hardcoded kubeconfig. Should take value from settings.py
=> Feature/SK-173 Fix hardcoded kubeconfig path

components/studio/apps/tasks.py
Fix post delete hooks raises NoneType object has no attribute "app".
=> Fix post delete hooks NoneType error
